openapi: 3.0.3

components:
  schemas:
    WebClickstreamEvent:
      type: object
      properties:
        event_id:
          type: string

        email:
          type: string
          format: email

        contact_id:
          type: string

        event_type:
          type: string

        product_sku:
          type: string

        event_value:
          type: number

        page_url:
          type: string
          format: url

        source_channel:
          type: string

        campaign_id:
          type: string

        event_timestamp:
          type: string
          format: date-time